spring:
  config:
    activate:
      on-profile: local
  # db설정 (kr.co.springboot_was_base.config.datasource 패키지 안에서 bean으로 관리)
  datasource:
    postgresql:
      url: "jdbc:postgresql://localhost:5432/swb"
      driver-class-name: "org.postgresql.Driver"
      user-name: "springboot-was-base-user"
      password: "springboot-was-base"
    oracle:
      url: "jdbc:oracle:thin:@localhost:1521:xe"
      driver-class-name: "oracle.jdbc.OracleDriver"
      user-name: "swb"
      password: "swb"
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  packages-to-scan: kr.co.springboot_was_base.api
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: springboot was base local api swagger
  version: v1.0.0
  description: springboot was base api project description
  cache:
    disabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  servers:
    - url: http://localhost:8080
      description: Localhost Server
    - url: http://localhost:8081
      description: Localhost Server 2
    - url: http://localhost:8082
      description: Localhost Server 3