spring:
  application:
    name: springboot-was-base
  datasource:
    url: jdbc:postgresql://localhost:5432/swb
    username: springboot-was-base-user
    password: springboot-was-base
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  docker:
    compose:
      enabled: true
      file: ./docker-compose.yml
