spring:
  profiles:
    active: local # 기본으로 활성화할 profile
  application:
    name: springboot-was-base
  docker:
    compose:
      enabled: true
      file: classpath:/docker/springboot-was-base/docker-compose-${spring.profiles.active}.yml
logging:
  config: classpath:/log4j2/log4j2-${spring.profiles.active}.xml