version: '3.8'
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      ORACLE_ALLOW_REMOTE: true
    ports:
      - "1521:1521"
    volumes:
      - swb-oracle-data:/opt/oracle
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: springboot-was-base-user
      POSTGRES_PASSWORD: springboot-was-base
      POSTGRES_DB: swb
      TZ: "Asia/Seoul"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  swb-oracle-data:
  postgres-data:
  redis-data:

  # oracle 초기 init
  # system / oracle
  # create user swb identified by swb;
  # GRANT CONNECT , RESOURCE , DBA TO swb;
  # COMMIT;